### ISSUE TITLE
Missing another firmware problem

### ISSUE THREAD

**Issue by JSBmanD** [Golovin-Andrey/xiaomi-mi-13-ubuntu#4]
`W: Possible missing firmware /lib/firmware/i915/kbl_dmc_ver1_01.bin for module i915`

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915/kbl_dmc_ver1_01.bin

**Comment by Golovin-Andrey** [comment]
Hi, could you clearify the problem? I suggest to install intell video drivers from 01.org
Soon I will add this steps to how to

**Comment by JSBmanD** [comment]
On some step, I saw this message. So, I installed this and all is ok.

**Comment by ghost** [comment]
I can confirm; this is a "general" Intel graphics warning (not error!) message. It isn't unique for the Xiaomi. The Dell of my other half, which also has Intel graphics, is displaying exactly the same error message. My production box with NVIDIA doesn't.
AFAIK the problem is that Intel graphics are detected, but not "specified" (?). Hence, ALL Intel firmware is expected. For example, my Xiaomi Air 12 has a Skylake. However, the firmware for Kabylake graphics (i.e. warning message of OP) is then also expected, which seems rather silly. You can install the firmware from e.g. 01.org like @Golovin-Andrey writes, but the message will return with a new update.
Ignoring the warning message has no ill effects.
If you want you can check your graphics in use with `lshw -c video`
